driver:
  name: vagrant
  customize:
    # NOTE: Memory is increased to 1024 for consistency across all environments
    #       MySQL server installation tends to fail with less than this
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16.42

platforms:
  - name: ubuntu/xenial64 # 16.04
  - name: ubuntu/trusty64 # 14.04
  - name: centos/7        # 7.3
  - name: centos/6        # 6.8
  - name: debian/jessie64 # 8
  - name: debian/wheezy64 # 7

suites:
  - name: server
    run_list: cop_mysql::install_server
    attributes:
        mysql:
            users:
                vagrant:
                    databases: [ 'test_db', 'test_db2' ]
                    host: '%'
                    grants: [ 'all' ]
                    password: 'Q7uwx4vMq]492*Cuhchk'
            databases: [ 'test_db', 'test_db1', 'test_db2' ]
  - name: client
    run_list: cop_mysql::install_client
    attributes:
