driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04.1
    driver:
      box: ubuntu-16.04.1
      box_url: https://s3.amazonaws.com/copiousdev/vagrant/ubuntu-16.04-xenial.box
  - name: bento/centos-7.2

suites:
  - name: server
    run_list: cop_mysql::default
    attributes:
        mysql:
            install_server: true
            install_client: true
            users:
                vagrant:
                    database: 'test_db'
                    grants: [ 'all' ]
                    password: 'Q7uwx4vMq]492*Cuhchk'
            databases: [ 'test_db' ]
  - name: client
    run_list: cop_mysql::default
    attributes:
        mysql:
            install_server: false
            install_client: true
