driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04.1
    driver:
      box: ubuntu-16.04.1
      box_url: https://s3.amazonaws.com/copiousdev/vagrant/ubuntu-16.04-xenial.box
  - name: bento/centos-7.2

suites:
  - name: server
    run_list: cop_mysql::install_server
    attributes:
        mysql:
            users:
                vagrant:
                    databases: [ 'test_db', 'test_db2' ]
                    host: '%'
                    grants: [ 'all' ]
                    password: 'Q7uwx4vMq]492*Cuhchk'
            databases: [ 'test_db', 'test_db1', 'test_db2' ]
  - name: client
    run_list: cop_mysql::install_client
    attributes:
